sudo: false
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script: vendor/bin/phpunit